name: Test Coverage

on:
  push:
    branches:
      - main
      - ci/test
  pull_request:

jobs:
  test_coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    env:
      SHA_SHORT: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      
      - run: echo "<h1>Foobar</h1>" > tarpaulin-report.html
      # - name: Install Rust toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     profile: minimal
      #     toolchain: stable
      #     override: true

      # - name: Run tarpaulin
      #   uses: actions-rs/tarpaulin@v0.1
      #   with:
      #     out-type: Html

      - if: ${{ github.event_name == 'pull_request' }}
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
        shell: bash

      - if: ${{ github.event_name == 'push' }}
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
        shell: bash

      - run: |
          TIME=$(TZ=UTC git show --quiet --date='format-local:%Y%m%dT%H%M%SZ' --format="%cd")
          SHA=${GITHUB_SHA:0:8}
          SLUG=$(echo ${BRANCH_NAME}_${TIME}_${SHA} | sed -r 's/[^[:alnum:]_-]/-/g')
          echo "SLUG=$SLUG" >> $GITHUB_ENV
        shell: bash

      - run: mv tarpaulin-report.html test_coverage_${{ env.SLUG }}.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: test_coverage_${{ env.SLUG }}
          path: test_coverage_${{ env.SLUG }}.html